### ISSUE TITLE
How do you draw terrain?

### ISSUE THREAD

**Issue by Venemo** [alacarte-maps/alacarte#63]
Hi,

I'm using alacarte with great success, but one thing I haven't been able to figure out yet is how to ask it to draw terrain, for example contour lines. I know that OSM should be capable of this, at least there is a cycle map on openstreetmap.org which contains contour lines (it even has labels that tell the altitude for each contour line).

Can you please tell me how to draw them using alacarte?

Thanks,
Timur

**Comment by Semoar** [comment]
Hi Timur,

unfortunately these lines aren't directly included into the OSM data, [1] describes how the cycle map does it and they use data from NASA and a specialized tool chain.

Maybe you could try to do something similar, but instead of generating shapefiles you could add the contour to the XML file. The Srtm2OSM script [2] looks helpful for this.

Best regards,
Simon

[1] http://wiki.openstreetmap.org/wiki/Contours
[2] http://wiki.openstreetmap.org/wiki/Srtm2Osm

**Comment by florianjacob** [comment]
Please reopen if you run into more problems with which we can help you.

We'd be happy to see examples or to include a guide if or as soon as you manage to do it. :+1:

**Comment by Venemo** [comment]
Thanks, I'll let you know how it goes!
